name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: gcc main.c
    - name: upload build artifact
      uses: actions/upload-artifact@v4.6.0
      with:
       name: Build-Artifact
       path: ${{github.workspace}}/a.out
       
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: test
      run: echo "hello how are you?"

  Deployment:
    runs-on: ubuntu-latest
    needs: test
    environment: dev-test
    
    steps:
    - name: test
      run: echo "this is deployment environment"
       

