name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: gcc main.c
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
     -name: test
      run: echo "hello test done"
       

