name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: gcc main.c
    - name: upload build artifact
      uses: actions/upload-artifact@v4.6.0
      with:
       name: Build-Artifact
       path: ${{github.workspace}}/a.out
       
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: test
      run: echo "hello how are you?"

  Deployment:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: dev-test
    
    steps:
    - name: deploy
      run: echo "this is deployment environment"
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
       name: Build-Artifact
    # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
       path: ${{github.workspace}}
       

